# Generated by Django 5.2.16 on 2026-08-07 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are', models.TextField(default='EduDirect is an education initiative built to guide learners through every step of their Malta journey.')),
                ('mission_statement', models.TextField(default='To equip international learners with the language, skills, cultural awareness, and pre-departure confidence they need to settle, study, and succeed in Malta.')),
                ('our_approach', models.JSONField(default=list, help_text='List of approach bullet points')),
                ('who_we_serve', models.TextField(default='Students, workers, families, and professionals preparing for life in Malta or strengthening their place in Maltese society.')),
                ('blended_learning_model', models.JSONField(default=list, help_text='List of blended learning model points')),
                ('blended_learning_benefits', models.JSONField(default=list, help_text='List of blended learning benefits')),
                ('courses_overview', models.TextField(default='EduDirect programmes are designed to work together or stand alone. Start with pre-departure readiness, build workplace skills with SkillPass, grow your Maltese through i Belong Stage One and Two, and deepen cultural understanding with Culture Stage 2.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 Education Street, Learning City, 10101')),
                ('phone', models.CharField(default='+1 234 567 8900', max_length=50)),
                ('email', models.EmailField(default='contact@educonnect.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Fri: 9:00 AM - 6:00 PM', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('source_page', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Addressed', 'Addressed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Learn • Grow • Succeed', max_length=100)),
                ('hero_title_main', models.CharField(default='Your Future', max_length=200)),
                ('hero_title_highlight', models.CharField(default='Starts Here', max_length=200)),
                ('hero_description', models.TextField(default='Discover world-class courses, learn from experts, and achieve your academic and career goals.')),
                ('hero_image_url', models.CharField(blank=True, default='/edu_banner.png', max_length=500)),
                ('notice_alert', models.CharField(blank=True, default='Summer term registration deadlines have been extended.', max_length=500, null=True)),
                ('active_announcement', models.CharField(blank=True, default='Dr. Foster appointed as Computer Science research head.', max_length=500, null=True)),
                ('stat_students', models.IntegerField(default=50000, help_text='Students Enrolled')),
                ('stat_courses', models.IntegerField(default=1200, help_text='Online Courses')),
                ('stat_partners', models.IntegerField(default=150, help_text='University Partners')),
                ('stat_rating', models.FloatField(default=4.8, help_text='Student Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, help_text='Optional URL to navigate when clicked', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
