# Generated by Django 5.2.16 on 2026-07-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('source_page', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_trained', models.PositiveIntegerField(default=0)),
                ('courses_offered', models.PositiveIntegerField(default=0)),
                ('placement_rate', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('partner_companies', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Institute Statistic',
                'verbose_name_plural': 'Institute Statistics',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/')),
            ],
        ),
    ]
