# Generated by Django 5.2.16 on 2026-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Learn • Grow • Succeed', max_length=100)),
                ('hero_title_main', models.CharField(default='Your Future', max_length=200)),
                ('hero_title_highlight', models.CharField(default='Starts Here', max_length=200)),
                ('hero_description', models.TextField(default='Discover world-class courses, learn from experts, and achieve your academic and career goals.')),
                ('hero_image_url', models.CharField(blank=True, default='/edu_banner.png', max_length=500)),
                ('stat_students', models.IntegerField(default=50000, help_text='Students Enrolled')),
                ('stat_courses', models.IntegerField(default=1200, help_text='Online Courses')),
                ('stat_partners', models.IntegerField(default=150, help_text='University Partners')),
                ('stat_rating', models.FloatField(default=4.8, help_text='Student Rating')),
            ],
        ),
        migrations.DeleteModel(
            name='InstituteStat',
        ),
    ]
