# Generated by Django 5.2.16 on 2026-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagesetting_delete_institutestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(default='Our mission is to provide accessible, high-quality education to empower learners globally.')),
                ('vision_statement', models.TextField(default='To be the leading platform for professional and academic growth.')),
                ('history_content', models.TextField(default='Founded in 2026, EduConnect has grown to serve thousands of students.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 Education Street, Learning City, 10101')),
                ('phone', models.CharField(default='+1 234 567 8900', max_length=50)),
                ('email', models.EmailField(default='contact@educonnect.com', max_length=254)),
                ('working_hours', models.CharField(default='Mon - Fri: 9:00 AM - 6:00 PM', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Addressed', 'Addressed')], default='Pending', max_length=20),
        ),
    ]
