# Generated by Django 5.2.16 on 2026-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutussetting_contactussetting_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesetting',
            name='active_announcement',
            field=models.CharField(blank=True, default='Dr. Foster appointed as Computer Science research head.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='notice_alert',
            field=models.CharField(blank=True, default='Summer term registration deadlines have been extended.', max_length=500, null=True),
        ),
    ]
