# Generated by Django 5.2.16 on 2026-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutussetting',
            name='history_content',
        ),
        migrations.RemoveField(
            model_name='aboutussetting',
            name='vision_statement',
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='blended_learning_benefits',
            field=models.JSONField(default=list, help_text='List of blended learning benefits'),
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='blended_learning_model',
            field=models.JSONField(default=list, help_text='List of blended learning model points'),
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='courses_overview',
            field=models.TextField(default='EduDirect programmes are designed to work together or stand alone. Start with pre-departure readiness, build workplace skills with SkillPass, grow your Maltese through i Belong Stage One and Two, and deepen cultural understanding with Culture Stage 2.'),
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='our_approach',
            field=models.JSONField(default=list, help_text='List of approach bullet points'),
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='who_we_are',
            field=models.TextField(default='EduDirect is an education initiative built to guide learners through every step of their Malta journey.'),
        ),
        migrations.AddField(
            model_name='aboutussetting',
            name='who_we_serve',
            field=models.TextField(default='Students, workers, families, and professionals preparing for life in Malta or strengthening their place in Maltese society.'),
        ),
        migrations.AlterField(
            model_name='aboutussetting',
            name='mission_statement',
            field=models.TextField(default='To equip international learners with the language, skills, cultural awareness, and pre-departure confidence they need to settle, study, and succeed in Malta.'),
        ),
    ]
