# Generated by Django 5.2.16 on 2026-07-23 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('attendance', models.IntegerField(default=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('enrollmentDate', models.DateField(auto_now_add=True)),
                ('gpa', models.FloatField(default=0.0)),
                ('outstandingFees', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
