# Generated by Django 5.2.16 on 2026-07-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_facultyprofile'),
        ('courses', '0008_classschedule_meeting_link_batch_classschedule_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.batch'),
        ),
    ]
