# Generated by Django 5.2.16 on 2026-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
    ]
