# Generated by Django 5.2.16 on 2026-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='exam_answers/'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='status',
            field=models.CharField(choices=[('Missed', 'Missed'), ('Submitted', 'Submitted - Pending Evaluation'), ('Evaluated', 'Evaluated')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('Written', 'Written Answer'), ('Photo', 'Photo Upload')], default='MCQ', max_length=20),
        ),
    ]
