# Generated by Django 5.2.16 on 2026-07-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentanswer_attachment_alter_examsubmission_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='proctoring_evidence/')),
                ('description', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='exams.examsubmission')),
            ],
        ),
    ]
