# Generated by Django 5.2.16 on 2026-07-28 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_malpracticelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpracticelog',
            name='submission',
        ),
        migrations.AddField(
            model_name='malpracticelog',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='exams.scheduledexam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malpracticelog',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
