# Generated by Django 5.2.16 on 2026-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('authorName', models.CharField(max_length=100)),
                ('authorRole', models.CharField(max_length=100)),
                ('authorAvatar', models.ImageField(blank=True, null=True, upload_to='blog/avatars/')),
                ('isDraft', models.BooleanField(default=False)),
                ('metaTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('metaDescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
