# Generated by Django 5.2.16 on 2026-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL to the course banner image', max_length=500, null=True),
        ),
    ]
