# Generated by Django 5.2.16 on 2026-07-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Business, IT, Data, Commerce', max_length=100, null=True),
        ),
    ]
