# Generated by Django 5.2.16 on 2026-07-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom/Google Meet link for online classes', null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, help_text='Specific fee for this batch', max_digits=10)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Offline', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.batch'),
        ),
    ]
