# Generated by Django 5.2.16 on 2026-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_classschedule_meeting_link_batch_classschedule_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='schedule_type',
            field=models.CharField(choices=[('Specific Date', 'Specific Date'), ('Recurring', 'Recurring')], default='Recurring', max_length=20),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='For specific date schedules', null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.CharField(blank=True, help_text='For recurring schedules', max_length=20, null=True),
        ),
    ]
