# Generated by Django 5.2.16 on 2026-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_classschedule_schedule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
