# Generated by Django 5.2.16 on 2026-08-05 11:17

from django.db import migrations, models
from django.utils.text import slugify


def populate_department_slugs(apps, schema_editor):
    Department = apps.get_model('courses', 'Department')
    for dept in Department.objects.all():
        base = slugify(dept.name) or f"dept-{dept.pk}"
        slug = base
        counter = 1
        while Department.objects.filter(slug=slug).exclude(pk=dept.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        dept.slug = slug
        dept.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        # Since the column 'slug' and its index already exist in the database due to the partial crash, 
        # we separate database and state. We tell Django's state that the field is added and unique, 
        # but we execute NO SQL against the database, perfectly syncing them.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='department',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=255, unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(populate_department_slugs, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Category',
        ),
    ]