# Generated by Django 5.2.16 on 2026-08-05 11:17

from django.db import migrations, models
from django.utils.text import slugify


def populate_department_slugs(apps, schema_editor):
    Department = apps.get_model('courses', 'Department')
    for dept in Department.objects.all():
        base = slugify(dept.name) or f"dept-{dept.pk}"
        slug = base
        counter = 1
        while Department.objects.filter(slug=slug).exclude(pk=dept.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        dept.slug = slug
        dept.save(update_fields=['slug'])

def drop_stale_slug_relations(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # Drop the column if it exists, which cascades to most indexes
        try:
            cursor.execute('ALTER TABLE "courses_department" DROP COLUMN IF EXISTS "slug" CASCADE;')
        except Exception:
            pass
        
        # Forcefully drop the indexes if they somehow survived
        try:
            cursor.execute('DROP INDEX IF EXISTS "courses_department_slug_197afd4f_like";')
        except Exception:
            pass
        try:
            cursor.execute('DROP INDEX IF EXISTS "courses_department_slug_key";')
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RunPython(drop_stale_slug_relations, migrations.RunPython.noop),
        # Step 1: Add field WITHOUT unique
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        # Step 2: Fill unique slugs for existing rows
        migrations.RunPython(populate_department_slugs, migrations.RunPython.noop),
        # Step 3: Now make it unique
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
