# Generated by Django 5.2.16 on 2026-08-07 06:06

from django.db import migrations, models
from django.utils.text import slugify


def populate_department_slugs(apps, schema_editor):
    Department = apps.get_model('courses', 'Department')
    for dept in Department.objects.all():
        base = slugify(dept.name) or f"dept-{dept.pk}"
        slug = base
        counter = 1
        while Department.objects.filter(slug=slug).exclude(pk=dept.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        dept.slug = slug
        dept.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='format_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_department_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='longDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
